### ISSUE TITLE
404 on project URL

### ISSUE THREAD

**Issue by cedroid09** [Humeira/made-in-Mauritius#10]
Hello Humeira,

I'm gettting error 404 while accessing the project url at http://echdee.ninja/made-in-mauritius/.
I attempted to access the-last-jedi project url as well with the same error.

Regards,
cedric

**Comment by Humeira** [comment]
Hi, 

Sorry about that, I moved them. I'll post the new links when my new server is ready.

You can access them here :

https://humeira.github.io/made-in-Mauritius/
https://humeira.github.io/the-last-jedi-countdown/
